# Generated by Django 5.2.7 on 2025-10-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_cwsnprofile_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text='Hide user from listings and disable new requests.'),
        ),
        migrations.AddField(
            model_name='user',
            name='suspension_reason',
            field=models.TextField(blank=True, help_text='Why the moderator suspended them (spam, fake info, etc.)', null=True),
        ),
    ]
