# Generated by Django 5.2.7 on 2025-10-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_suspended_user_suspension_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='cwsnprofile',
            name='availability_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy')], default='Available', help_text="Caregiver's current availability status.", max_length=20),
        ),
        migrations.AddField(
            model_name='cwsnprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text="Moderator has verified this caregiver's qualifications."),
        ),
        migrations.AddField(
            model_name='cwsnprofile',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Comments about verification (optional).', null=True),
        ),
    ]
