# Generated by Django 5.2.7 on 2025-10-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='moderator_action',
            field=models.TextField(blank=True, help_text='[Moderator only] Action taken or notes.', null=True),
        ),
    ]
